import java.time.LocalDate;
import java.util.UUID;

public record Expense(UUID id, LocalDate date, double amount, Category category, String description) {
    public Expense {
        if (id == null){
            throw new IllegalArgumentException("ID cannot be null.");
        }
        if (date == null){
            throw new IllegalArgumentException("Date cannot be null.");
        }
        if (date.isAfter(LocalDate.now())){
            throw new IllegalArgumentException("Date field cannot be in the future.");
        }
        if (amount <= 0){
            throw new IllegalArgumentException("The amount must be strictly positive.");
        }
        if (category == null){
            throw new IllegalArgumentException("Category field cannot be null.");
        }
        if (description == null || description.isBlank()){
            throw new IllegalArgumentException("Description cannot be null or blank.");
        }
        description = description.trim();
    }

    // constructor for creating an expense with autogenerated id and timestamp
    public Expense(double amount, Category category, String description){
        this(UUID.randomUUID(), LocalDate.now(), amount, category, description);
    }

    // helper function for generating a expense into a csv row
    public String toCSVRow(){
        String escapedDescription = description.replace("\"", "\"\"");
        return String.join(",", id.toString(), date.toString(), Double.toString(amount), category.name(), "\"" + escapedDescription +"\"" );

    }
}
