import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

public record Transaction(UUID id, String accountNumber, TransactionType type, double amount, LocalDateTime timestamp, TransactionStatus status, String description) {

    // constructor transaction for validation
    public Transaction{
        Objects.requireNonNull(id, "Transaction ID cannot be null");
        Objects.requireNonNull(accountNumber, "Account number cannot be null");
        Objects.requireNonNull(type, "Transaction type cannot be null");
        Objects.requireNonNull(timestamp, "Timestamp cannot be null");
        Objects.requireNonNull(status, "Status cannot be null");

        if (amount < 0){
            throw new IllegalArgumentException("Transaction amount cannot be negative");
        }
    }

    // constructor transaction for creating new transactions with autogenerated id and timestamp
    public Transaction(String accountNumber, TransactionType type, double amount, TransactionStatus status, String description){
        this(UUID.randomUUID(), accountNumber, type, amount, LocalDateTime.now(), status, description);
    }


    // helper function to write data of transaction into a csv row
    public String toCSVRow(){
        return String.join(",", id.toString(), accountNumber, type.name(),String.valueOf(amount), timestamp.toString(), status.name(), "\"" + (description != null ? description : "") + "\'" );
    }

}
